version: '3'
# Other docker-compose examples in /examples

services:
  minecraft:
    ports:
      - "25565:25565"
    volumes:
      - "mc:/data"
      - "mc:/plugins"
    environment:
      EULA: "TRUE"
      CONSOLE: "false"
      ENABLE_RCON: "false"
      CUSTOM_SERVER: "server.jar"
    restart: always

volumes:
  mc: