#!/bin/bash

. /start-utils

log "Using custom server jar at ${CUSTOM_SERVER} ..."
cp /tmp/${CUSTOM_SERVER} "$SERVER_PROPERTIES"
export SERVER=${CUSTOM_SERVER}

export SKIP_LOG4J_CONFIG=true

# Continue to Final Setup
exec /start-finalSetup01ServerProperties $@
