#!/bin/bash

. /start-utils

shopt -s nullglob

#umask 002
export HOME=/data

if [ ! -e /data/eula.txt ]; then
  EULA="${EULA,,}"
  if [ "$EULA" != "true" ]; then
    log ""
    log "Please accept the Minecraft EULA at"
    log "  https://account.mojang.com/documents/minecraft_eula"
    log "by adding the following immediately after 'docker run':"
    log "  -e EULA=TRUE"
    log ""
    exit 1
  fi

  echo "# Generated via Docker on $(date)" > /data/eula.txt

  if ! echo "eula=$EULA" >> /data/eula.txt; then
    log "ERROR: unable to write eula to /data. Please make sure attached directory is writable by uid=${UID}"
    exit 2
  fi
fi


log "Running as uid=$(id -u) gid=$(id -g) with /data as '$(ls -lnd /data)'"

if ! touch /data/.verify_access; then
  log "ERROR: /data doesn't seem to be writable. Please make sure attached directory is writable by uid=$(id -u)"
  exit 2
fi

rm /data/.verify_access || true

export SERVER_PROPERTIES=/data/server.properties

cd /data || exit 1
exec /start-deployCustom "$@"