#!/bin/bash

. /start-utils

log "Using custom server jar at server.jar ..."
cp /tmp/server.jar "server.jar"
export SERVER="server.jar"

export SKIP_LOG4J_CONFIG=true

# Continue to Final Setup
exec /start-finalSetup01ServerProperties $@
